### ISSUE TITLE
Can this library be dropped in place of the official one to work with existing app?

### ISSUE THREAD

**Issue by jankais3r** [HyroVitalyProtago/LeapMotionRemoteUnity#1]
Hi,

Apologies if this is a stupid question. I am currently looking into ways to make Leap Motion usable on Windows ARM. Windows 10/11 for ARM can run x86 and x64 apps, but drivers have to be native. Since Ultraleap does not provide ARM-compatible drivers, it will have to be some remote solution - that's how I found your library.

My question is this: if I have an existing, compiled Unity app that uses the official Leap SDK, can I create a new project using LeapMotionRemoteUnity, compile it, take the resulting Leap DLL file and drop it in in place of the DLL that was shipped with the Unity app in question? Would that work?

Thank you

**Comment by HyroVitalyProtago** [comment]
Hi!

No question is stupid ;)

The problem is that Leap DLL is never recompiled in LeapMotionRemoteUnity, I only modifies some files in the Unity package. So you just need to update the files in the Unity project, setup ip and enable remote in unity editor and build the project again. I imagine that you haven't access to the Unity project if you want to swap a DLL in a compiled Unity app? In this case, it's maybe possible but I don't know exactly how to do... You'll probably need to decompile the Assembly-CSharp.dll in Data/Managed/ with https://www.jetbrains.com/decompiler/ for example (also the original project needs to have unobfuscated/unsecured dll), add/modify files from LeapMotionRemoteUnity (that's the part I've never done and don't know exactly how to do it, maybe it's easy to create a Visual Studio project and recompile a new dll with the added/modified files) + set hardcoded value (ip,remoteEnable) cause you haven't access to the unity editor, recompile it and swap the previous dll.

**Comment by jankais3r** [comment]
So the apps I would like to use your modified library with, have the following folder structure with LeapC.dll being a separate file.

<img width="719" alt="Screen Shot 2021-10-25 at 23 37 08" src="https://user-images.githubusercontent.com/2159464/138775015-cb76e823-07f6-4914-9ebc-e9ca73159624.png">

I have a "template" project that will result in similar folder structure as well, hence my question if I can expect  these LeapC.dll libraries to be interoperable - the official one expecting local Leap controller, or yours looking for the ws://, while the rest of the functionality and API calls remain compatible. Or are you saying that none of the changes made by your library end up in this LeapC.dll?

**Comment by HyroVitalyProtago** [comment]
Yes, I don't change the LeapC.dll.

When you look at a Unity project that use Leap Motion, you can see that the DLLs are already provided by Leap.
![image](https://user-images.githubusercontent.com/3470988/138831506-34472e78-86ce-479c-bb44-befb545ec72e.png)

What we change is files in LeapCSharp that is a C# wrapper to call the DLL. And this files is only compiled like the other scripts in unity project in Assembly-CSharp.dll that you can find in the Managed folder under the Data folder of the build (only visible in your Portrait Demos because you've used il2cpp for HoloBoing).
![image](https://user-images.githubusercontent.com/3470988/138831698-9c64deb9-8656-40c9-afd1-9934f284da1e.png)

So if you have the Unity project, you can just change the files in it and rebuild it so it works. If you only have the builds, it's maybe possible for those that haven't used il2cpp with the trick that I've explained before with Assembly-CSharp.dll.

**Comment by jankais3r** [comment]
Many thanks for your detailed explanation. I have no prior Unity experience, so this information you provided will help me immensely.
